language: php

php:
  - 7.1

cache:
  directories:
    -$HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit
  - phpenv config-rm xdebug.ini || return 0
  - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix